### ISSUE TITLE
Different buttons

### ISSUE THREAD

**Issue by maxfact** [franksouza183/Evolvere-Dark-Aurorae-theme#1]
hello I installed the window decoration but does not match the preview contained in the file, I attach the image
I am using kde plasma 5.12, qt 5.10.1, kde frameworks 5.43.0 on archlinux
![screenshot_20180302_102810](https://user-images.githubusercontent.com/6670325/36892298-9d292c38-1e04-11e8-9d6e-3f8e3525cf1d.png)
Why on my system is this?

**Comment by franksouza183** [comment]
Hi, @maxfact, I'll investigate this.

**Comment by franksouza183** [comment]
I just tried on a fresh install with arch and latest plasma-desktop. No problems here. This is a simple aurorae theme, could you test with these themes and see if this also happens?

https://www.opendesktop.org/p/1002630/
https://www.opendesktop.org/p/1002632/
https://www.opendesktop.org/p/1002631/

**Comment by maxfact** [comment]
I think I have a problem with my configuration of arch, I will try a new installation to understand where my problem is

**Comment by franksouza183** [comment]
No problem, if you find the evolvere aurorae theme as the source of the problem, we can reopen this issue
